[package]
name = "step_wise_mini_lsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-skiplist = "0.1"
anyhow = "1"
arc-swap = "1"
bytes = "1"
parking_lot = "0.12"
ouroboros = "0.18"